#
# Copyright (C) 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/blu/G0771

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

# Platform
TARGET_BOARD_PLATFORM := ums9230
BOARD_VENDOR := blu

# Header v4 & Vendor Boot
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_USES_VENDOR_BOOT := true
TARGET_NO_KERNEL := false

# Prebuilt Kernel & DTB
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img

# Partitions & Sizes
BOARD_BOOTIMG_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_FLASH_BLOCK_SIZE := 262144

# Dynamic Partitions (Super)
BOARD_SUPER_PARTITION_SIZE := 4294967296
BOARD_SPARSE_SUPER_PARTITION := true
BOARD_SUPER_PARTITION_GROUPS := main_group
BOARD_MAIN_GROUP_SIZE := 4294967296
BOARD_MAIN_GROUP_PARTITION_LIST := system system_ext vendor product

# File Systems
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4

# Recovery Specifics
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_THEME := portrait_hdpi
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_TOOLBOX := true